spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concurrency
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

